%瑞利信道
rayChan = comm.RayleighChannel( ...
    "SampleRate",96000,...
    "MaximumDopplerShift",13,...
    "PathDelays",[0 10e-3 15e-3],...
    "AveragePathGains",[0,-3,-3],...
    "Visualization",'Impulse response');
tx = randi([0 1],500,1);
dbspkMod = comm.DBPSKModulator;
dpskSig = dbspkMod(tx);
y = rayChan(dpskSig);
