%莱斯信道
fs = 3.84e6;
pathDelay = [0 200 800 1200 2300 3700]*1e-9;
avgPathGains = [0 -0.9 -4.9 -8 -7.8 -23.9];
kfact = 10;
fD = 50;
ricianChan = comm.RicianChannel('SampleRate',fs,...
    'AveragePathGains',avgPathGains,...
    'PathDelays',pathDelay,...
    'KFactor',kfact,...
    'MaximumDopplerShift',fD,...
    'Visualization','Impulse and frequency responses');
tx = randi([0 1],500,1);
dbspkMod = comm.DBPSKModulator;
dpskSig = dbspkMod(tx);
y = ricianChan(dpskSig);
